//==============================================================================
//####TCAT-SOURCE-HEADER-BEGIN####
//
// This confidential and proprietary source may be used only as authorized
// by a licensing agreement from TC Applied Technologies.
//
// Copyright (c) 2004-2013 TC Applied Technologies
//                         a division of TC Group Americas Ltd.
//                         All rights reserved.
//
// Unauthorized use, duplication or distribution of this source is strictly
// prohibited by law.
//
// The entire notice above must be reproduced on all authorized copies and
// copies may only be made to the extent permitted by a licensing agreement
// from TC Applied Technologies.
//
//####TCAT-SOURCE-HEADER-END####
//==============================================================================

#ifndef _TCAT_DICE_MACROS_H_
#define _TCAT_DICE_MACROS_H_


///////////////////////////////////////////////////////////////////////////////
//
//	TCAT defines
//
///////////////////////////////////////////////////////////////////////////////
//
//	here are the legal copyright information. 
//
#define kTCAT_DICE_PROVIDER						TC Applied Technologies
#define kTCAT_DICE_DRIVER_PROVIDER				TC Applied Technologies
#define kTCAT_DICE_COPYRIGHT					(c) kTCAT_DICE_PROVIDER 2004-2013
#define kTCAT_DICE_COPYRIGHT_DRIVER				(c) kTCAT_DICE_DRIVER_PROVIDER 2004-2013



///////////////////////////////////////////////////////////////////////////////
//
//	stringify/concatenation macros
//
///////////////////////////////////////////////////////////////////////////////
//
#define __TCAT_STRINGIFY(x)					#x
#define __TCAT_LSTRINGIFY(x)				L#x
#define __TCAT_CAT_VERSION(mj,mn,s,b)		mj##.##mn##.##s##.##b
#define __TCAT_CAT_VERSION_SHORT(mj,mn,s)	mj##.##mn##.##s
#define __TCAT_CAT(x,y)						x##y
#define __TCAT_CONJ(x,y)					x##,##y

#define TCAT_STRINGIFY(x)					__TCAT_STRINGIFY(x)
#define TCAT_LSTRINGIFY(x)					__TCAT_LSTRINGIFY(x)
#define TCAT_CAT_VERSION(mj,mn,s,b)			__TCAT_CAT_VERSION(mj,mn,s,b)
#define TCAT_CAT_VERSION_SHORT(mj,mn,s)		__TCAT_CAT_VERSION_SHORT(mj,mn,s)
#define TCAT_CAT(x,y)						__TCAT_CAT(x,y)
#define TCAT_CONJ(x,y)						__TCAT_CONJ(x,y)



///////////////////////////////////////////////////////////////////////////////
//
//	generated defines
//
///////////////////////////////////////////////////////////////////////////////
//
//	this defines will be generated out of the information given above and
//	usually there should be no need of changing the following
//
//	USR defines are used to present driver names etc. to the user
//
#define kTCAT_DICE_USR_STR						TCAT_STRINGIFY	(kTCAT_DICE_USR)
#define kTCAT_DICE_USR_LSTR						TCAT_LSTRINGIFY	(kTCAT_DICE_USR)

// if you prefer you can append a " MIDI", " ASIO", etc to the user display names (see SPDIF/AC3):
#define kTCAT_DICE_USR_ASIO						ASIO kTCAT_DICE_USR
#define kTCAT_DICE_USR_AUDIO					kTCAT_DICE_USR // Audio
#define kTCAT_DICE_USR_AUDIO_INF				kTCAT_DICE_USR Audio
#define kTCAT_DICE_USR_AUDIO_STEREO_PAIR		kTCAT_DICE_USR Stereo Pair
#define kTCAT_DICE_USR_AUDIO_MIXER_INF			kTCAT_DICE_USR Audio Mixer
#define kTCAT_DICE_USR_MIDI						kTCAT_DICE_USR // MIDI
#define kTCAT_DICE_USR_MIDI_INF					kTCAT_DICE_USR MIDI
#define kTCAT_DICE_USR_SPDIF_AC3				kTCAT_DICE_USR SPDIF/AC3
#define kTCAT_DICE_USR_SPDIF_PCM				kTCAT_DICE_USR SPDIF/PCM
#define kTCAT_DICE_USR_CPL						kTCAT_DICE_USR Control Panel
#define kTCAT_DICE_USR_MIXER					kTCAT_DICE_USR // Mixer

#define kTCAT_DICE_USR_ASIO_STR					TCAT_STRINGIFY	(kTCAT_DICE_USR_ASIO)
#define kTCAT_DICE_USR_AUDIO_STR				TCAT_STRINGIFY	(kTCAT_DICE_USR_AUDIO)
#define kTCAT_DICE_USR_AUDIO_LSTR				TCAT_LSTRINGIFY	(kTCAT_DICE_USR_AUDIO)
#define kTCAT_DICE_USR_AUDIO_INF_STR			TCAT_STRINGIFY	(kTCAT_DICE_USR_AUDIO_INF)
#define kTCAT_DICE_USR_AUDIO_INF_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_USR_AUDIO_INF)
#define kTCAT_DICE_USR_AUDIO_STEREO_PAIR_STR	TCAT_STRINGIFY	(kTCAT_DICE_USR_AUDIO_STEREO_PAIR)
#define kTCAT_DICE_USR_AUDIO_STEREO_PAIR_LSTR	TCAT_LSTRINGIFY	(kTCAT_DICE_USR_AUDIO_STEREO_PAIR)
#define kTCAT_DICE_USR_AUDIO_MIXER_INF_STR		TCAT_STRINGIFY	(kTCAT_DICE_USR_AUDIO_MIXER_INF)
#define kTCAT_DICE_USR_AUDIO_MIXER_INF_LSTR		TCAT_LSTRINGIFY	(kTCAT_DICE_USR_AUDIO_MIXER_INF)
#define kTCAT_DICE_USR_MIDI_STR					TCAT_STRINGIFY	(kTCAT_DICE_USR_MIDI)
#define kTCAT_DICE_USR_MIDI_LSTR				TCAT_LSTRINGIFY	(kTCAT_DICE_USR_MIDI)
#define kTCAT_DICE_USR_MIDI_INF_STR				TCAT_STRINGIFY	(kTCAT_DICE_USR_MIDI_INF)
#define kTCAT_DICE_USR_MIDI_INF_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_USR_MIDI_INF)
#define kTCAT_DICE_USR_SPDIF_AC3_STR			TCAT_STRINGIFY	(kTCAT_DICE_USR_SPDIF_AC3)
#define kTCAT_DICE_USR_SPDIF_AC3_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_USR_SPDIF_AC3)
#define kTCAT_DICE_USR_SPDIF_PCM_STR			TCAT_STRINGIFY	(kTCAT_DICE_USR_SPDIF_PCM)
#define kTCAT_DICE_USR_SPDIF_PCM_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_USR_SPDIF_PCM)
#define kTCAT_DICE_USR_MIXER_LSTR				TCAT_LSTRINGIFY	(kTCAT_DICE_USR_MIXER)
#define kTCAT_DICE_USR_CPL_STR					TCAT_STRINGIFY	(kTCAT_DICE_USR_CPL)
#define kTCAT_DICE_USR_PROVIDER_STR				TCAT_STRINGIFY	(kTCAT_DICE_PROVIDER)
#define kTCAT_DICE_USR_VENDOR_STR				TCAT_STRINGIFY	(kTCAT_DICE_VENDOR)
#define kTCAT_DICE_USR_COPYRIGHT_STR			TCAT_STRINGIFY	(kTCAT_DICE_COPYRIGHT)
#define kTCAT_DICE_USR_COPYRIGHT_DRIVER_STR		TCAT_STRINGIFY	(kTCAT_DICE_COPYRIGHT_DRIVER)




//	DRV defines are used to internally identify device and driver
//
#define kTCAT_DICE_DRV_STR						TCAT_STRINGIFY	(kTCAT_DICE_DRV)
#define kTCAT_DICE_DRV_LSTR						TCAT_LSTRINGIFY	(kTCAT_DICE_DRV)
#define kTCAT_DICE_DRV_INF						TCAT_CAT		(kTCAT_DICE_DRV,.inf)
#define kTCAT_DICE_DRV_INF_STR					TCAT_STRINGIFY	(kTCAT_DICE_DRV_INF)
#define kTCAT_DICE_DRV_CAT						TCAT_CAT		(kTCAT_DICE_DRV,.cat)
#define kTCAT_DICE_DRV_SYS						TCAT_CAT		(kTCAT_DICE_DRV,.sys)
#define kTCAT_DICE_DRV_SYS_STR					TCAT_STRINGIFY	(kTCAT_DICE_DRV_SYS)
#define kTCAT_DICE_DRV_CLIENT					TCAT_CAT		(kTCAT_DICE_DRV,UserClient)
#define kTCAT_DICE_DRV_CLIENT_STR				TCAT_STRINGIFY	(kTCAT_DICE_DRV_CLIENT)

#define kTCAT_DICE_DRV_AUDIO					TCAT_CAT		(kTCAT_DICE_DRV,Audio)
#define kTCAT_DICE_DRV_AUDIO_STR				TCAT_STRINGIFY	(kTCAT_DICE_DRV_AUDIO)
#define kTCAT_DICE_DRV_AUDIO_LSTR				TCAT_LSTRINGIFY	(kTCAT_DICE_DRV_AUDIO)

#define kTCAT_DICE_DRV_AUDIOMIXER				TCAT_CAT		(kTCAT_DICE_DRV,AudioMixer)
#define kTCAT_DICE_DRV_AUDIOMIXER_STR			TCAT_STRINGIFY	(kTCAT_DICE_DRV_AUDIOMIXER)
#define kTCAT_DICE_DRV_AUDIOMIXER_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_DRV_AUDIOMIXER)

#define kTCAT_DICE_DRV_AUDIO_SYS				TCAT_CAT		(kTCAT_DICE_DRV_AUDIO,.sys)
#define kTCAT_DICE_DRV_AUDIO_SYS_STR			TCAT_STRINGIFY	(kTCAT_DICE_DRV_AUDIO_SYS)
#define kTCAT_DICE_DRV_AUDIO_SYS_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_DRV_AUDIO_SYS)
#define kTCAT_DICE_DRV_AUDIO_ID_LSTR			kTCAT_DICE_DRV_LSTR L"\\Audio&" kTCAT_DICE_DRV_LOCATION_LSTR L"\0"
#define kTCAT_DICE_DRV_AUDIO_CLASS_LSTR			kTCAT_DICE_DRV_LSTR L"#Audio&" kTCAT_DICE_DRV_LOCATION_LSTR L"#\0"
#define kTCAT_DICE_DRV_AUDIO_ID_COMPATIBLE_LSTR	kTCAT_DICE_DRV_LSTR L"\\CompatibleAudio\0"
#define kTCAT_DICE_DRV_AUDIO_ENGINE				TCAT_CAT		(kTCAT_DICE_DRV_AUDIO,Engine)
#define kTCAT_DICE_DRV_AUDIO_ENGINE_STR			TCAT_STRINGIFY	(kTCAT_DICE_DRV_AUDIO_ENGINE)
#define kTCAT_DICE_DRV_AUDIO_STREAM				TCAT_CAT		(kTCAT_DICE_DRV_AUDIO,Stream)
#define kTCAT_DICE_DRV_AUDIO_STREAM_STR			TCAT_STRINGIFY	(kTCAT_DICE_DRV_AUDIO_STREAM)
#define kTCAT_DICE_DRV_ASYNCREQ					TCAT_CAT		(kTCAT_DICE_DRV,AsyncReq)
#define kTCAT_DICE_DRV_ISOCPORT					TCAT_CAT		(kTCAT_DICE_DRV,IsocPort)
#define kTCAT_DICE_DRV_ISOCPORT_STR				TCAT_STRINGIFY	(kTCAT_DICE_DRV_ISOCPORT)
#define kTCAT_DICE_DRV_AC3						TCAT_CAT		(kTCAT_DICE_DRV,Ac3)
#define kTCAT_DICE_DRV_AC3_STR					TCAT_STRINGIFY	(kTCAT_DICE_DRV_AC3)
#define kTCAT_DICE_DRV_AC3_LSTR					TCAT_LSTRINGIFY	(kTCAT_DICE_DRV_AC3)
#define kTCAT_DICE_DRV_ASIO						TCAT_CAT		(kTCAT_DICE_DRV,Asio)
#define kTCAT_DICE_DRV_ASIO_DLL					TCAT_CAT		(kTCAT_DICE_DRV_ASIO,.dll)
#define kTCAT_DICE_DRV_ASIO_DLL_STR				TCAT_STRINGIFY	(kTCAT_DICE_DRV_ASIO_DLL)
#define kTCAT_DICE_DRV_MIDI						TCAT_CAT		(kTCAT_DICE_DRV,Midi)
#define kTCAT_DICE_DRV_MIDI_STR					TCAT_STRINGIFY	(kTCAT_DICE_DRV_MIDI)
#define kTCAT_DICE_DRV_MIDI_LSTR				TCAT_LSTRINGIFY	(kTCAT_DICE_DRV_MIDI)
#define kTCAT_DICE_DRV_MIDI_SYS					TCAT_CAT		(kTCAT_DICE_DRV_MIDI,.sys)
#define kTCAT_DICE_DRV_MIDI_SYS_STR				TCAT_STRINGIFY	(kTCAT_DICE_DRV_MIDI_SYS)
#define kTCAT_DICE_DRV_MIDI_SYS_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_DRV_MIDI_SYS)
#define kTCAT_DICE_DRV_MIDI_CLASS_IN_LSTR		kTCAT_DICE_DRV_LSTR L"#MidiIn#\0"
#define kTCAT_DICE_DRV_MIDI_CLASS_OUT_LSTR		kTCAT_DICE_DRV_LSTR L"#MidiOut#\0"
#define kTCAT_DICE_DRV_MIDI_ID_IN_LSTR			kTCAT_DICE_DRV_LSTR L"\\MidiIn\0"
#define kTCAT_DICE_DRV_MIDI_ID_OUT_LSTR			kTCAT_DICE_DRV_LSTR L"\\MidiOut\0"
#define kTCAT_DICE_DRV_MIDI_ID_COMPATIBLE_LSTR	kTCAT_DICE_DRV_LSTR L"\\CompatibleMidi\0"
#define kTCAT_DICE_DRV_CPL						TCAT_CAT		(kTCAT_DICE_DRV,.cpl)
#define kTCAT_DICE_DRV_CPL_STR					TCAT_STRINGIFY	(kTCAT_DICE_DRV_CPL)
#define kTCAT_DICE_DRV_CPL_EXE					TCAT_CAT		(kTCAT_DICE_DRV,.exe)
#define kTCAT_DICE_DRV_CPL_EXE_STR				TCAT_STRINGIFY	(kTCAT_DICE_DRV_CPL_EXE)
#define kTCAT_DICE_DRV_LOCATION					Adapter%02d
#define kTCAT_DICE_DRV_LOCATION_LSTR			TCAT_LSTRINGIFY	(kTCAT_DICE_DRV_LOCATION)
#ifdef WIN32
#define kTCAT_DICE_DRV_SYMLINK					"\\\\.\\" kTCAT_DICE_DRV_STR
#else
#define kTCAT_DICE_DRV_SYMLINK					kTCAT_DICE_DRV_STR
#endif

#define kTCAT_DICE_CPL_PATH						Control Panel Binary Path	///< Registry Key for specifying the Control Panel Binary (exe) -- Windows only.
#define kTCAT_DICE_CPL_PATH_STR					TCAT_STRINGIFY(kTCAT_DICE_CPL_PATH)

#define kTCAT_DICE_CONFIG_APP_BUNDLE_ID_STR		TCAT_STRINGIFY(kTCAT_DICE_CONFIG_APP_BUNDLE_ID)


//	version format
//		0xFMmsbbbb
//		  F			Flags	- build flags indicating type and origin of binary
//		  1M		Major	- cosmetic number PM decides 
//			m		minor	- increase at interface change
//			 s		sub		- increase at release for bug fix, feature change, w/o interface change
//			  bbbb	build	- reflecting SVN revision
//
#define kTCAT_DICE_VERSION_MASK_COMPATIBILITY	0x3ff00000
#define kTCAT_DICE_VERSION_MASK_MAJOR			0x1f000000
#define kTCAT_DICE_VERSION_MASK_MINOR			0x00f00000
#define kTCAT_DICE_VERSION_MASK_SUB				0x000f0000
#define kTCAT_DICE_VERSION_MASK_BUILD			0x0000ffff
#define kTCAT_DICE_VERSION_MASK_BUILDSERVER		0x80000000
#define kTCAT_DICE_VERSION_MASK_INSTRUMENTED	0x40000000
#define kTCAT_DICE_VERSION_MASK_BETA			0x20000000	// included in compatibility bitmask

#define TCAT_VERSION32_MAJOR(v32)		(((v32)&kTCAT_DICE_VERSION_MASK_MAJOR)>>24)
#define TCAT_VERSION32_MINOR(v32)		(((v32)&kTCAT_DICE_VERSION_MASK_MINOR)>>20)
#define TCAT_VERSION32_SUB(v32)			(((v32)&kTCAT_DICE_VERSION_MASK_SUB)>>16)
#define TCAT_VERSION32_BUILD(v32)		((v32)&kTCAT_DICE_VERSION_MASK_BUILD)
#define TCAT_VERSION32(M,m,s,b)			(((M)<<24)|((m)<<20)|((s)<<16)|((b)))

#if kTCAT_DICE_VERSION_BUILDSERVER
#define kTCAT_DICE_VERSION_BLDSRVR_BIT	kTCAT_DICE_VERSION_MASK_BUILDSERVER
#else
#define kTCAT_DICE_VERSION_BLDSRVR_BIT	0
#endif

#ifdef _DEBUG
#define kTCAT_DICE_VERSION_INSTR_BIT	kTCAT_DICE_VERSION_MASK_INSTRUMENTED
#else
#define kTCAT_DICE_VERSION_INSTR_BIT	0
#endif//TCAT_DEBUG

#if kTCAT_DICE_VERSION_BETA
#define kTCAT_DICE_VERSION_BETA_BIT		kTCAT_DICE_VERSION_MASK_BETA
#else
#define kTCAT_DICE_VERSION_BETA_BIT		0
#endif

#define kTCAT_DICE_VERSION32			(TCAT_VERSION32(kTCAT_DICE_VERSION_MAJOR,kTCAT_DICE_VERSION_MINOR,kTCAT_DICE_VERSION_SUB,kTCAT_DICE_VERSION_BUILD) | kTCAT_DICE_VERSION_BLDSRVR_BIT | kTCAT_DICE_VERSION_INSTR_BIT | kTCAT_DICE_VERSION_BETA_BIT)
#define kTCAT_DICE_VERSION				TCAT_CAT_VERSION(kTCAT_DICE_VERSION_MAJOR,kTCAT_DICE_VERSION_MINOR,kTCAT_DICE_VERSION_SUB,kTCAT_DICE_VERSION_BUILD)

#if kTCAT_DICE_VERSION_BUILDSERVER
#define kTCAT_DICE_VERSION_PRE1			kTCAT_DICE_VERSION
#else
#define kTCAT_DICE_VERSION_PRE1			kTCAT_DICE_VERSION local
#endif //kTCAT_DICE_VERSION_BUILDSERVER
#if kTCAT_DICE_VERSION_BETA
#define kTCAT_DICE_VERSION_PRE2			kTCAT_DICE_VERSION_PRE1 beta
#else
#define kTCAT_DICE_VERSION_PRE2			kTCAT_DICE_VERSION_PRE1
#endif //kTCAT_DICE_VERSION_BETA
#ifdef _DEBUG
#define kTCAT_DICE_VERSION_EXTENDED		kTCAT_DICE_VERSION_PRE2 instrumented
#else
#define kTCAT_DICE_VERSION_EXTENDED		kTCAT_DICE_VERSION_PRE2
#endif //_DEBUG

#define kTCAT_DICE_VERSION_STR			TCAT_STRINGIFY(kTCAT_DICE_VERSION)
#define kTCAT_DICE_VERSION_LSTR			TCAT_LSTRINGIFY(kTCAT_DICE_VERSION)
#define kTCAT_DICE_VERSION_EXTENDED_STR	TCAT_STRINGIFY(kTCAT_DICE_VERSION_EXTENDED)
#define kTCAT_DICE_VERSION_SHORT		TCAT_CAT_VERSION_SHORT(kTCAT_DICE_VERSION_MAJOR,kTCAT_DICE_VERSION_MINOR,kTCAT_DICE_VERSION_SUB)
#define kTCAT_DICE_VERSION_RC			kTCAT_DICE_VERSION_MAJOR,kTCAT_DICE_VERSION_MINOR,kTCAT_DICE_VERSION_SUB,kTCAT_DICE_VERSION_BUILD

#define kTCAT_DICE_VERSION_MAJOR_STRING TCAT_STRINGIFY(TCAT_CAT(000,kTCAT_DICE_VERSION_MAJOR))
#define kTCAT_DICE_VERSION_MINOR_STRING	TCAT_STRINGIFY(TCAT_CAT(000,kTCAT_DICE_VERSION_MINOR))
#define kTCAT_DICE_VERSION_SUB_STRING	TCAT_STRINGIFY(TCAT_CAT(000,kTCAT_DICE_VERSION_SUB))
#define kTCAT_DICE_VERSION_BUILD_STRING	TCAT_STRINGIFY(kTCAT_DICE_VERSION_BUILD)

#define kTCAT_DICE_VERSION_MAGIC_STRING			"56448A3A-77AB-4631-A34D-5CD917EE4B24"
#define kTCAT_DICE_VERSION_NEW_MAGIC_STRING		"B3F35591-997E-43dc-92BC-0904EFE8BC2B"


#endif  //_TCAT_DICE_MACROS_H_
