///////////////////////////////////////////////////////////////////////////////
//
// This confidential and proprietary software may be used only as authorised
// by a licensing agreement from TC Applied Technologies Ltd.
//
// (C) COPYRIGHT 2008-2013 TC Applied Technologies Ltd. (ALL RIGHTS RESERVED)
//
// Unauthorized use, duplication or distribution of this software is  
// strictly prohibited by law.
//
// The entire notice above must be reproduced on all authorised copies and
// copies may only be made to the extent permitted by a licensing agreement
// from TC Applied Technologies Ltd.
//
///////////////////////////////////////////////////////////////////////////////
//
//         ****** DO NOT EDIT THIS FILE ******
//
// This file is auto-generated by a script.
//
// Generated on :  Jun 14 03:54:49 2013
// From XML file:  http://www.tctechnologies.tc/appdata/ohci1394db.xml
//
///////////////////////////////////////////////////////////////////////////////


const VENDOR_INFO vendors[] =
{
	// Adaptec http://www.adaptec.com/
	{ TEXT("9004"), TEXT("5800"), TEXT("2"), TEXT("2"), TEXT("Adaptec"), TEXT("AIC-5800"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },

	// ALi http://www.ali.com.tw/
	{ TEXT("10b9"), TEXT("5251"), TEXT("Unknown"), TEXT("Unknown"), TEXT("Acer Laboratories, Inc."), TEXT("M5251"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("1025"), TEXT("5251"), TEXT("Unknown"), TEXT("Unknown"), TEXT("Acer Laboratories, Inc."), TEXT("M5251"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("10b9"), TEXT("5253"), TEXT("8"), TEXT("4"), TEXT("Acer Laboratories, Inc."), TEXT("M5253/M5271"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },

	// Creative http://www.creative.com/
	{ TEXT("1102"), TEXT("4001"), TEXT("8"), TEXT("4"), TEXT("Creative"), TEXT("Audigy/EMU10K1"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// Fujitsu http://www.fujitsu.com/
	{ TEXT("10cf"), TEXT("200c"), TEXT("4"), TEXT("4"), TEXT("Fujitsu"), TEXT("MB86613"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// Intel http://www.intel.com/
	{ TEXT("8086"), TEXT("7605"), TEXT("Unknown"), TEXT("Unknown"), TEXT("Intel"), TEXT("82372FB"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// JMicron http://www.jmicron.com/
	{ TEXT("197b"), TEXT("2380"), TEXT("Unknown"), TEXT("Unknown"), TEXT("JMicron Technology"), TEXT("JMB380/JMB381/JMB383"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },

	// LSI/Agere/Lucent http://www.lsi.com/
	{ TEXT("11c1"), TEXT("5811"), TEXT("8"), TEXT("8"), TEXT("LSI (Agere, Lucent)"), TEXT("FW321/FW322/FW323"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("11c1"), TEXT("5903"), TEXT("8"), TEXT("8"), TEXT("LSI (Agere, Lucent)"), TEXT("FW533"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },
	{ TEXT("11c1"), TEXT("5901"), TEXT("8"), TEXT("8"), TEXT("LSI (Agere, Lucent)"), TEXT("FW643"), FW_INTERFACES_MAX_SPEED_S800, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },

	// National Semiconductor http://www.national.com/
	{ TEXT("100b"), TEXT("000f"), TEXT("8"), TEXT("8"), TEXT("National Semiconductor"), TEXT("CS4210"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// NEC http://www.necel.com/
	{ TEXT("1033"), TEXT("0063"), TEXT("4"), TEXT("4"), TEXT("NEC Electronics"), TEXT("D72862"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("1033"), TEXT("00cd"), TEXT("4"), TEXT("4"), TEXT("NEC Electronics"), TEXT("D72870"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_LIMITED },
	{ TEXT("1033"), TEXT("00ce"), TEXT("4"), TEXT("4"), TEXT("NEC Electronics"), TEXT("D72871/D72872"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("1033"), TEXT("00e7"), TEXT("4"), TEXT("4"), TEXT("NEC Electronics"), TEXT("D72873"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("1033"), TEXT("00f2"), TEXT("4"), TEXT("4"), TEXT("NEC Electronics"), TEXT("D72874"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },

	// NVIDIA http://www.nvidia.com/
	{ TEXT("10de"), TEXT("006e"), TEXT("Unknown"), TEXT("Unknown"), TEXT("NVIDIA"), TEXT("nForce MCP2"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// O2Micro http://www.o2micro.com/
	{ TEXT("1217"), TEXT("ffff"), TEXT("Unknown"), TEXT("Unknown"), TEXT("O2Micro International"), TEXT("OZxxxx"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// OPTi http://www.opti.com/
	{ TEXT("1045"), TEXT("c881"), TEXT("4"), TEXT("4"), TEXT("OPTi"), TEXT("82C881"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// Ricoh http://www.ricoh.com/LSI/
	{ TEXT("1180"), TEXT("0551"), TEXT("4"), TEXT("4"), TEXT("Ricoh"), TEXT("R5C551"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("1180"), TEXT("0552"), TEXT("4"), TEXT("4"), TEXT("Ricoh"), TEXT("R5C552"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("1180"), TEXT("0554"), TEXT("4"), TEXT("4"), TEXT("Ricoh"), TEXT("R5C553"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("1180"), TEXT("0832"), TEXT("4"), TEXT("4"), TEXT("Ricoh"), TEXT("R5C832"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },

	// SiS Silicon Integrated Systems http://www.sis.com/
	{ TEXT("1039"), TEXT("7007"), TEXT("Unknown"), TEXT("Unknown"), TEXT("Silicon Integrated Systems"), TEXT("7007"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// Sony http://www.sony.com
	{ TEXT("104d"), TEXT("8009"), TEXT("2"), TEXT("2"), TEXT("Sony"), TEXT("CDX1947"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("104d"), TEXT("8039"), TEXT("4"), TEXT("4"), TEXT("Sony"), TEXT("CDX3222"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },

	// TI http://www.ti.com/
	{ TEXT("104c"), TEXT("8000"), TEXT("Unknown"), TEXT("Unknown"), TEXT("Texas Instruments"), TEXT("TSB12LV21A/TSB12LV21B"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller is not compatible with DICE drivers."), FW_INTERFACES_SUPPORT_LEVEL_NONE },
	{ TEXT("104c"), TEXT("8009"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB12LV22"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },
	{ TEXT("104c"), TEXT("8019"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB12LV23"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },
	{ TEXT("104c"), TEXT("8020"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB12LV26"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },
	{ TEXT("104c"), TEXT("8026"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB43AB21A"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("104c"), TEXT("8021"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB43AA22"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("104c"), TEXT("8022"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB43AB22"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("104c"), TEXT("8023"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB43AB22A"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("104c"), TEXT("8024"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB43AB23"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("104c"), TEXT("8025"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("TSB82AA2B/TSB83AA22A/TSB83AA23"), FW_INTERFACES_MAX_SPEED_S800, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("104c"), TEXT("8235"), TEXT("4"), TEXT("4"), TEXT("Texas Instruments"), TEXT("XIO2200A"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("104c"), TEXT("823f"), TEXT("8"), TEXT("4"), TEXT("Texas Instruments"), TEXT("XIO2213"), FW_INTERFACES_MAX_SPEED_S800, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },

	// VIA http://www.via.com.tw/
	{ TEXT("1106"), TEXT("0130"), TEXT("4"), TEXT("4"), TEXT("VIA Technologies"), TEXT("VT6305"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN },
	{ TEXT("1106"), TEXT("3040"), TEXT("8"), TEXT("8"), TEXT("VIA Technologies"), TEXT("VT6306"), FW_INTERFACES_MAX_SPEED_S400, TEXT("This controller has been verified to work with DICE drivers with limited capability. On some older motherboards, it may only support a limited number of audio channels."), FW_INTERFACES_SUPPORT_LEVEL_LIMITED },
	{ TEXT("1106"), TEXT("3044"), TEXT("8"), TEXT("4"), TEXT("VIA Technologies"), TEXT("VT6307/VT6308"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },
	{ TEXT("1106"), TEXT("3403"), TEXT("8"), TEXT("4"), TEXT("VIA Technologies"), TEXT("VT6315/VT6330"), FW_INTERFACES_MAX_SPEED_S400, TEXT(""), FW_INTERFACES_SUPPORT_LEVEL_FULL },

	{ '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', FW_INTERFACES_SUPPORT_LEVEL_UNKNOWN }
};
